name: Merge upstream master branch
on:
  schedule:
  - cron: "0 */6 * * *"
  push:
    branches:
    - master
jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        repository: ShubhamTatvamasi/magma
        token: ${{ secrets.GH_PAT }}

    - name: Merge Upstream
      run: |
        git config --global user.name 'Shubham Tatvamasi'
        git config --global user.email 'shubhamtatvamasi@gmail.com'

        git remote add upstream https://github.com/magma/magma.git
        git pull --rebase upstream master

        git push origin master
